// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbzIaMNKcY-IOFsrOtsbCiTVDlEzWVcDk',
    appId: '1:73619817305:web:fcff268bab57e9c8cc8248',
    messagingSenderId: '73619817305',
    projectId: 'my-flutterproject-quiz',
    authDomain: 'my-flutterproject-quiz.firebaseapp.com',
    databaseURL: 'https://my-flutterproject-quiz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutterproject-quiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDloVNoPsIBsxDP1svx_pF-sH1K2iofo',
    appId: '1:73619817305:android:b55d7b7a19f7165acc8248',
    messagingSenderId: '73619817305',
    projectId: 'my-flutterproject-quiz',
    databaseURL: 'https://my-flutterproject-quiz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutterproject-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkaOWNNOJunX0mr3rC7i99yYxpKL_yAno',
    appId: '1:73619817305:ios:1580d2184420f7f5cc8248',
    messagingSenderId: '73619817305',
    projectId: 'my-flutterproject-quiz',
    databaseURL: 'https://my-flutterproject-quiz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutterproject-quiz.appspot.com',
    iosBundleId: 'com.luminar.quiz.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkaOWNNOJunX0mr3rC7i99yYxpKL_yAno',
    appId: '1:73619817305:ios:98bce59c976c1960cc8248',
    messagingSenderId: '73619817305',
    projectId: 'my-flutterproject-quiz',
    databaseURL: 'https://my-flutterproject-quiz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-flutterproject-quiz.appspot.com',
    iosBundleId: 'com.luminar.quiz.quizApp.RunnerTests',
  );
}
